image: r-base

test:
  script:
    - apt-get install -y libcurl4-openssl-dev
    -  R -e 'install.packages(c("rstan"))
    #- R -e 'install.packages(c("Rcpp", "RcppParallel", "V8", "rstan",  "rstantools", "testthat", "BH", "RcppEigen", "StanHeaders"))'
    #- R CMD build . --no-build-vignettes --no-manual
    #- R CMD check *tar.gz --no-build-vignettes --no-manual