image: r-base

# For Mac OS and Windows use tags 'R' (version 3.6.3) or 'R4' depending of the R version needed.
# Authors : Jean-François Rey <jean-francois.rey@inrae.fr>

stages: 
  - create
  - tests
  - build

R-base-create:
  stage: create
  script:
    # generate Documentation
    - "Rscript -e \"roxygen2::roxygenize('.', roclets=c('rd', 'collate', 'namespace'))\""
    # create the package
    - "R CMD build . --resave-data"
  artifacts:
    paths:
      # keep the package for later jobs
      - "$(ls -rt *_*.tar.gz |tail -1)"
      # can use $CI_PROJECT_NAME if package name the same

R-Mac-create:
  stage: create
  tags:
    - "Mac"  
    - "R4"
  script:
    - "Rscript -e \"roxygen2::roxygenize('.', roclets=c('rd', 'collate', 'namespace'))\""
    - "R CMD build . --resave-data"
  artifacts:
    paths:
      - "$(ls -rt *_*.tar.gz |tail -1)"

R-Windows-create:
  stage: create
  tags:
    - "win10"
    - "R4"
  script:
    - "Rscript -e \"roxygen2::roxygenize('.', roclets=c('rd', 'collate', 'namespace'))\""
    - "R CMD build . --resave-data"
  artifacts:
    paths:
      - "$(ls -rt *_*.tar.gz |tail -1)"

R-base-tests:
  stage: tests
  script:
    - "R CMD check --as-cran $(ls -rt *_*.tar.gz |tail -1)"
  artifacts:
    paths:
      - "$(ls -rt *_*.tar.gz |tail -1)"
  dependencies:
    - R-base-create

R-Mac-tests:
  stage: tests
  tags:
    - "Mac"  
    - "R4"
  script:
    - "sleep 120" # time for ntp update
    - "R CMD check --as-cran $(ls -rt *_* |tail -1)"
  artifacts:
    paths:
      - "$(ls -rt *_*.tar.gz |tail -1)"
  dependencies:
    - R-Mac-create

R-Windows-tests:
  stage: tests
  tags:
    - "win10"
    - "R4"
  script:
    - "R CMD check --as-cran $(ls -rt *_*.tar.gz |tail -1)"
  artifacts:
    paths:
      - "$(ls -rt *_*.tar.gz |tail -1)"
  dependencies:
    - R-Windows-create

release-R:
  stage: build
  script:
    - "echo \"Nothing to do\""
  artifacts:
    paths:
      - "$(ls -rt *_* |tail -1)"
  only:
    - tags
  dependencies:
    - R-base-tests

release-Windows:
  stage: build
  tags:
    - "win10"
    - "R4"
  script:
    - "R CMD INSTALL --build --force-biarch $(ls -rt *_*.tar.gz |tail -1)"
  artifacts:
    paths:
      - "$(ls -rt *_*.zip |tail -1)"
  only:
    - tags
  dependencies:
    - R-Windows-tests

release-MacOS:
  stage: build
  tags:
    - "Mac"  
    - "R4"
  script:
    - "sleep 120" # time for ntp update
    - "R CMD INSTALL --build $(ls -rt *_*.tar.gz |tail -1)"
  artifacts:
    paths:
      - "$(ls -rt *_*.tgz | tail -1)"
  only:
    - tags
  dependencies:
    - R-Mac-tests








